title: Paceline / John Pollard

remote_theme: pages-themes/minimal@v0.2.0

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
