title: Paceline / John Pollard
description: Strategic Technology & Business Consulting
url: "https://jfpollard.github.io"
baseurl: "/paceline"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
