title: Paceline / John Pollard
description: an introduction to Paceline and John Pollard
url: "https://jfpollard.github.io"
baseurl: "/jfpollard.github.io"

theme: jekyll-theme-minimal

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
